# Generated by Django 2.2.1 on 2021-07-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendEmail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
